export const metadata = {
    title: 'About nextJS tutorial',
    description: 'Generated by learning Routing metadata for search engines optimization',
  }
  

export default function About () {
    return <h1>About</h1>;
}